# Generated by Django 3.0.5 on 2020-04-05 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200405_1458'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='created_date',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='published_date',
            new_name='updated',
        ),
    ]
