# Generated by Django 3.0.5 on 2020-04-16 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0002_comments_contents'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comments',
            new_name='Comment',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='contents',
            new_name='content',
        ),
    ]
