# Generated by Django 3.0.5 on 2020-04-08 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='contents',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
